# Generated by Django 6.0.1 on 2026-03-27 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='votes',
            field=models.IntegerField(default=0, help_text='Current tally for this candidate'),
        ),
        migrations.AlterField(
            model_name='question',
            name='description',
            field=models.TextField(blank=True, help_text='Optional context for the voter'),
        ),
        migrations.AlterField(
            model_name='question',
            name='is_text_answer',
            field=models.BooleanField(default=False, help_text='Check if this is an open-ended question'),
        ),
        migrations.AlterField(
            model_name='question',
            name='order',
            field=models.IntegerField(default=1, help_text='Determines the order on the ballot'),
        ),
    ]
