# Generated by Django 6.0.1 on 2026-03-27 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0002_alter_choice_votes_alter_question_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='deadline',
            field=models.DateTimeField(blank=True, help_text='The date and time when this poll closes and expires.', null=True),
        ),
    ]
