# Generated by Django 6.0.1 on 2026-03-28 07:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0004_alter_question_options_question_created_at_auditlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='voterprofile',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrator'), ('voter', 'Standard Voter')], default='voter', help_text='Determines dashboard access level.', max_length=10),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='choice',
            name='votes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='question',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
