# Generated by Django 6.0.1 on 2026-03-31 15:04

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0005_voterprofile_role_alter_auditlog_timestamp_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='timestamp',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='choice',
            name='votes',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='question',
            name='deadline',
            field=models.DateTimeField(blank=True, db_index=True, help_text='The date and time when this poll closes and expires.', null=True),
        ),
        migrations.AlterField(
            model_name='vote',
            name='voted_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='voterprofile',
            name='county',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='voterprofile',
            name='has_voted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='voterprofile',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrator'), ('voter', 'Standard Voter')], db_index=True, default='voter', help_text='Determines dashboard access level.', max_length=10),
        ),
        migrations.AddIndex(
            model_name='voterprofile',
            index=models.Index(fields=['county', 'has_voted'], name='voting_vote_county_3b3440_idx'),
        ),
    ]
